/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queues;

import java.util.ArrayList;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class GUI extends javax.swing.JFrame {
    
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        first = new javax.swing.JTextField();
        second = new javax.swing.JTextField();
        third = new javax.swing.JTextField();
        fourth = new javax.swing.JTextField();
        fifth = new javax.swing.JTextField();
        sixth = new javax.swing.JTextField();
        seventh = new javax.swing.JTextField();
        eight = new javax.swing.JTextField();
        ninght = new javax.swing.JTextField();
        tenth = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOutputLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        enter = new javax.swing.JTextField();
        txtInputLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        front = new javax.swing.JTextField();
        rear = new javax.swing.JTextField();
        enqueue = new javax.swing.JButton();
        dequeue = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Justine Favia Queue-Implementation");

        jPanel1.setBackground(java.awt.Color.blue);

        jPanel2.setBackground(new java.awt.Color(5, 147, 169));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(116, 112, 111), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        first.setEditable(false);
        first.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        first.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 30));

        second.setEditable(false);
        second.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        second.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(second, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 60, 30));

        third.setEditable(false);
        third.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        third.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(third, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 60, 30));

        fourth.setEditable(false);
        fourth.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        fourth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(fourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 30));

        fifth.setEditable(false);
        fifth.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        fifth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(fifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 61, 30));

        sixth.setEditable(false);
        sixth.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        sixth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(sixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 60, 30));

        seventh.setEditable(false);
        seventh.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        seventh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(seventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 61, 30));

        eight.setEditable(false);
        eight.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        eight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 61, 30));

        ninght.setEditable(false);
        ninght.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        ninght.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(ninght, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 60, 30));

        tenth.setEditable(false);
        tenth.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        tenth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(tenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 60, 30));

        output.setEditable(false);
        output.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 230, 66));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("0");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 18, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 15, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("2");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 34, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("3");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("4");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 20, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("5");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 20, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("6");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 30, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("7");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 16, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("8");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 20, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("9");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 15, -1));

        jLabel3.setBackground(new java.awt.Color(116, 112, 111));
        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CIRCULAR QUEUE");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 370, 60));

        txtOutputLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtOutputLabel.setForeground(java.awt.Color.white);
        txtOutputLabel.setText("OUTPUT");
        jPanel2.add(txtOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jPanel5.setBackground(new java.awt.Color(216, 196, 25));

        enter.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        enter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterKeyPressed(evt);
            }
        });

        txtInputLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtInputLabel.setForeground(java.awt.Color.white);
        txtInputLabel.setText("INPUT");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Front");

        front.setEditable(false);

        rear.setEditable(false);

        enqueue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enqueue.setText("Enqueue");
        enqueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enqueueActionPerformed(evt);
            }
        });

        dequeue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dequeue.setText("Dequeue");
        dequeue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dequeueActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Rear");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(54, 54, 54))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dequeue, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(txtInputLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(rear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(front, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(front, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(txtInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dequeue, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 280, 420));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enqueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enqueueActionPerformed
        txtOutputLabel.setText("OUTPUT");
        output.setText("");
        
        
        Circular_Queue.enQueue(Integer.valueOf(enter.getText()));
        
        if (Circular_Queue.rear == 0)
        {
            first.setText(String.valueOf(Circular_Queue.circular_queue.get(Circular_Queue.rear)));
        }   
        else if(Circular_Queue.rear == 1)
        {
            second.setText(String.valueOf(Circular_Queue.circular_queue.get(Circular_Queue.rear))); 
        }
        else if(Circular_Queue.rear == 2)
        {
            third.setText(String.valueOf(Circular_Queue.circular_queue.get(Circular_Queue.rear))); 
        }
        else if(Circular_Queue.rear == 3)
        {
            fourth.setText(String.valueOf(Circular_Queue.circular_queue.get(Circular_Queue.rear))); 
        }
        else if(Circular_Queue.rear == 4)
        {
            fifth.setText(String.valueOf(Circular_Queue.circular_queue.get(Circular_Queue.rear))); 
        }
        else if(Circular_Queue.rear == 5)
        {
            sixth.setText(String.valueOf(Circular_Queue.circular_queue.get(Circular_Queue.rear))); 
        }
        else if(Circular_Queue.rear == 6)
        {
            seventh.setText(String.valueOf(Circular_Queue.circular_queue.get(Circular_Queue.rear))); 
        }
        
        else if(Circular_Queue.rear == 7)
        {
            eight.setText(String.valueOf(Circular_Queue.circular_queue.get(Circular_Queue.rear))); 
        }
        
        else if(Circular_Queue.rear == 8)
        {
            ninght.setText(String.valueOf(Circular_Queue.circular_queue.get(Circular_Queue.rear))); 
        }
        else if(Circular_Queue.rear == 9)
        {
            tenth.setText(String.valueOf(Circular_Queue.circular_queue.get(Circular_Queue.rear))); 
        }

        front.setText(String.valueOf(Circular_Queue.front));
        rear.setText(String.valueOf(Circular_Queue.rear));
    }//GEN-LAST:event_enqueueActionPerformed

    private void dequeueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dequeueActionPerformed
        txtOutputLabel.setText("OUTPUT");
        output.setText("");
        
        String empty = "";
        enter.setText("");
        
              if (Circular_Queue.front == 0)
        {
            first.setText(empty);
        }   
        else if(Circular_Queue.front == 1)
        {
            second.setText(empty);
        }
        else if(Circular_Queue.front == 2)
        {
            third.setText(empty); 
        }
        else if(Circular_Queue.front == 3)
        {
            fourth.setText(empty);
        }
        else if(Circular_Queue.front == 4)
        {
            fifth.setText(empty);
        }
        else if(Circular_Queue.front == 5)
        {
            sixth.setText(empty);
        }
        else if(Circular_Queue.front == 6)
        {
            seventh.setText(empty);
        }
        
        else if(Circular_Queue.front == 7)
        {
            eight.setText(empty);
        }
        
        else if(Circular_Queue.front == 8)
        {
            ninght.setText(empty);
        }
        else if(Circular_Queue.front == 9)
        {
            tenth.setText(empty);
        }
        
        
    
        int index = Circular_Queue.deQueue();
        
        if(index == -1) {
            txtOutputLabel.setText("Warning!");
            output.setText("Empty Queue");
        }
        else {
            txtOutputLabel.setText("OUTPUT");
            output.setText(String.valueOf(index));
        }
        
        front.setText(String.valueOf(Circular_Queue.front));
        rear.setText(String.valueOf(Circular_Queue.rear));
    }//GEN-LAST:event_dequeueActionPerformed

    private void enterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterKeyPressed

        enter.addKeyListener(new KeyAdapter() {
            
        public void keyTyped(KeyEvent e) {
            char c = e.getKeyChar();
            if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                txtOutputLabel.setText("Warning!");
                output.setText("Please Enter an Integer value");
                e.consume();
            }
            }
        });
    }//GEN-LAST:event_enterKeyPressed

public class JTextFieldValidation extends JFrame {
   JTextField tf;
   Container container;
   JLabel label;
}    
    
public static class Circular_Queue{

public static int size, front, rear; //Variable declaration

public static ArrayList<Integer> circular_queue = new ArrayList<Integer>(); //Declaring Integer array list

Circular_Queue(int queue_size) //Constructor
{
	this.size = queue_size;
	this.front = this.rear = -1;
}

public static String enQueue(int queue_data) //Insertion Function
{
	if((front == 0 && rear == size - 1) ||
	(rear == (front - 1) % (size - 1))) // Condition if queue is full
	{
		return "Queue is Full";
	}

	else if(front == -1) // Condition for empty queue.
	{
		front = 0;
		rear = 0;
		circular_queue.add(rear, queue_data);
	}
	else if(rear == size - 1 && front != 0)
	{
		rear = 0;
		circular_queue.set(rear, queue_data);
	}
	else
	{
		rear = (rear + 1);
		// Adding a new element if
		if(front <= rear)
		{
			circular_queue.add(rear, queue_data);
		}
		// Else updating old value
		else
		{
			circular_queue.set(rear, queue_data);
		}
	}
        return "Element added";
}

public static int deQueue() //Dequeue Function
{
	int temp;

	if(front == -1) //Checking for empty queue
	{
		System.out.print("Queue Empty!");
		return -1;
	}

	temp = circular_queue.get(front);

	if(front == rear) // For only one element
	{
		front = -1;
		rear = -1;
	}

	else if(front == size - 1)
	{
		front = 0;
	}
	else
	{
		front = front + 1;
	}
	return temp; // Returns dequeued element
}

}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Circular_Queue queue = new Circular_Queue(10);
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {  
                
                
                
                new GUI().setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dequeue;
    private javax.swing.JTextField eight;
    private javax.swing.JButton enqueue;
    private javax.swing.JTextField enter;
    private javax.swing.JTextField fifth;
    private javax.swing.JTextField first;
    private javax.swing.JTextField fourth;
    private javax.swing.JTextField front;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ninght;
    private javax.swing.JTextField output;
    private javax.swing.JTextField rear;
    private javax.swing.JTextField second;
    private javax.swing.JTextField seventh;
    private javax.swing.JTextField sixth;
    private javax.swing.JTextField tenth;
    private javax.swing.JTextField third;
    private javax.swing.JLabel txtInputLabel;
    private javax.swing.JLabel txtOutputLabel;
    // End of variables declaration//GEN-END:variables

}
